config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: 'miniblogs#index'
    resources :miniblogs
    resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/miniblog.rb
class Miniblog < ApplicationRecord
    validates :text, presence: true
    
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :miniblogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :confirure_permitted_parameters, if: :devise_controller?
    
    private
    def confirure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/miniblogs_controller.rb
class MiniblogsController < ApplicationController
  before_action :set_miniblog, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]
    
    def index
      @miniblogs = Miniblog.includes(:user).order("created_at DESC")
    end
    
    def new
      @miniblog = Miniblog.new
    end
    
    def create
      Miniblog.create(miniblog_params)
      redirect_to root_path
    end
    
    def destroy
      miniblog = Miniblog.find(params[:id])
      miniblog.destroy
      redirect_to root_path
    end
    
    def edit
    end
    
    def update
      miniblog = Miniblog.find(params[:id])
      miniblog.update(miniblog_params)
      redirect_to root_path
    end
    
    def show
    end
    
    private #以下はプライベートメソッドを定義しています
    
    def miniblog_params
      params.require(:miniblog).permit(:text).merge(user_id: current_user.id)
    end
    
    def set_miniblog
      @miniblog = Miniblog.find(params[:id])
    end
    
    def move_to_index
      unless user_signed_in?
        redirect_to action: :index
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      user = User.find(params[:id])
      @nickname = user.nickname
      @miniblogs = user.miniblogs
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miniblogs_helper.rb
module MiniblogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Min</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="heading">
        <h1><%= link_to 'Blog', root_path, class: 'title' %></h1>
      </div>
      <div class="navbar">
        <ul class="nav-lists">
          <% if user_signed_in? %>
            <li class="nav-list to-my-page"><%= link_to 'User: ', "/users/#{current_user.id}", class: 'nav-list' %><span><%= current_user.nickname %></span></li>
            <li class="nav-list"><%= link_to 'SignOut', destroy_user_session_path, method: :delete, class: 'nav-list'%></li>
          <% else %>
            <li class="nav-list"><%= link_to 'SignUp', new_user_registration_path, class: 'nav-list'%></li>
            <li class="nav-list"><%= link_to 'SignIn', new_user_session_path, class: 'nav-list' %></li>
          <% end %>
          <li class="nav-list"><%= link_to 'New', new_miniblog_path, class: 'nav-list' %></li>
        </ul>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/miniblogs/edit.html.erb
<div class="content row">
    <div class="container">
        <h3>編集する</h3>
        <%= form_with(model: @miniblog, class: 'form',  local: true) do |form| %>
          <%= form.text_area :text, placeholder: "", rows: "10", class: 'text_area' %>
          <%= form.submit "SEND", class: 'submit-btn'%>
        <% end %>
    </div>
</div>

app/views/miniblogs/index.html.erb
<div class="contents row">
  <div class="container">
  <% @miniblogs.each do |miniblog| %>
      <div class="content_post">
        <p><%= miniblog.text %></p>
        <ul class="btn-lists">
          <li>
            <%= link_to 'SHOW', miniblog_path(miniblog.id), method: :get, class: 'btn-list' %>
          </li>
          <% if user_signed_in? && current_user.id == miniblog.user_id %>
          <li>
            <%= link_to 'EDIT', edit_miniblog_path(miniblog.id), method: :get, class: 'btn-list' %>
          </li>
          <li>
            <p  class="btn-list pull-down-list" id="clickButton">DESTROY</p>
          </li>
          <% end %>
        </ul>  
      </div>
      <div class="confirmation" id="confirmation_display_before_deletion">
        <h3>Are you sure?</h3>
        <ul>
          <li><p class="before-delete-btn" id="cancelButton">NO</p></li>
          <li><%= link_to 'OK', miniblog_path(miniblog.id), method: :delete, class: 'before-delete-btn'%></li>
        </ul>
      </div>
    <% end %>
  </div>
  </div>
  
  

app/views/miniblogs/new.html.erb
<div class="content row">
    <div class="container">
        <h3>本文</h3>
        <%= form_with(model: @miniblog, class: 'form',  local: true) do |form| %>
          <%= form.text_area :text, placeholder: "", rows: "10", class: 'text_area' %>
          <%= form.submit "SEND", class: 'submit-btn'%>
        <% end %>
    </div>
</div>

app/views/miniblogs/show.html.erb
<div class="contents row">
    <div class="content_post">
        <div class="container">
          <p><%= @miniblog.text %></p>
          <ul class="btn-lists btn_show_lists">
          <li>
            <%= link_to 'EDIT', edit_miniblog_path(@miniblog.id), method: :get, class: 'btn-list' %>
          </li>
          <li>
            <p  class="btn-list pull-down-list" id="clickButton">DESTROY</p>
          </li>
        </ul> 
        </div>
        <div class="confirmation" id="confirmation_display_before_deletion">
        <h3>Are you sure?</h3>
        <ul>
          <li><p class="before-delete-btn" id="cancelButton">NO</p></li>
          <li><%= link_to 'OK', miniblog_path(@miniblog.id), method: :delete, class: 'before-delete-btn'%></li>
        </ul>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<script scr="/projects/min/app/javascript/channels/index.js"></script>
<div class="contents row">
  <div class="container">
    <h3><%= @nickname %>さんの投稿一覧</h3>
    <% @miniblogs.each do |miniblog| %>
      <div class="content_post">
        <p><%= miniblog.text %></p>
        <ul class="btn-lists">
          <li>
            <%= link_to 'EDIT', edit_miniblog_path(miniblog.id), method: :get, class: 'btn-list' %>
          </li>
          <li>
            <p  class="btn-list pull-down-list" id="clickButton">DESTROY</p>
          </li>
        </ul>  
      </div>
      <div class="confirmation" id="confirmation_display_before_deletion">
        <h3>Are you sure?</h3>
        <ul>
          <li><p class="before-delete-btn" id="cancelButton">NO</p></li>
          <li><%= link_to 'OK', miniblog_path(miniblog.id), method: :delete, class: 'before-delete-btn'%></li>
        </ul>
      </div>
    <% end %>
  </div>  
</div>